---
abstract: 'Alien distribution for raylib video game engine, version 5 and above'
author:
  - 'Chris Prather C<< <chris at prather.org> >>, L<http://chris.prather.org>'
  - 'based on the work of Ahmad Fatoum C<< <athreef@cpan.org> >>, L<http://a3f.at>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.039'
  Alien::Build: '2.84'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.043, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-raylib5
provides:
  Alien::raylib5:
    file: lib/Alien/raylib5.pm
    version: '0.026'
version: '0.026'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
